[project]
name = "movies-lib-explorer"
version = "0.2.0"
description = "movies-lib-explorer"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.1.1,<7",
    "django-debug-toolbar>=8.0.0,<9",
    "django-filter>=26.1,<27",
    "django-grappelli>=5.0.0,<6",
    "django-htmx>=1.29.0,<2",
    "djangorestframework>=3.18.1,<4",
    "djangorestframework-xml>=2.0.0,<3",
    "pillow>=12.3.0,<13",
    "requests>=2.34.2,<3",
    "xlsxwriter>=3.2.9,<4",
]
