# Generated by Django 4.1 on 2022-11-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title', 'director__last_name', 'director__first_name'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='movie',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_company',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title', 'director'], name='catalog_mov_title_05772e_idx'),
        ),
    ]
