# Generated by Django 4.2.8 on 2024-01-16 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_actor_alter_director_options_director_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies_list_limit', models.IntegerField(default=2500, validators=[django.core.validators.MinValueValidator(1)])),
                ('people_list_limit', models.IntegerField(default=2500, validators=[django.core.validators.MinValueValidator(1)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
                'ordering': ['id'],
            },
        ),
    ]
