# Generated by Django 4.2.8 on 2024-01-21 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2099)]),
        ),
        migrations.AlterField(
            model_name='settings',
            name='movies_list_limit',
            field=models.IntegerField(default=2500, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3000)]),
        ),
        migrations.AlterField(
            model_name='settings',
            name='people_list_limit',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
