# Generated by Django 6.1.1 on 2026-09-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_movie_year_alter_settings_movies_list_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='ext_biography',
            field=models.CharField(blank=True, max_length=8000),
        ),
        migrations.AddField(
            model_name='actor',
            name='ext_birth_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='actor',
            name='ext_birth_place',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='actor',
            name='ext_death_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='actor',
            name='ext_imdb_id',
            field=models.CharField(blank=True, max_length=110),
        ),
        migrations.AddField(
            model_name='actor',
            name='ext_name',
            field=models.CharField(blank=True, max_length=110),
        ),
        migrations.AddField(
            model_name='actor',
            name='ext_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='actor',
            name='ext_picture_uri',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='actor',
            name='ext_tmdb_id',
            field=models.CharField(blank=True, max_length=110),
        ),
        migrations.AddField(
            model_name='director',
            name='ext_biography',
            field=models.CharField(blank=True, max_length=8000),
        ),
        migrations.AddField(
            model_name='director',
            name='ext_birth_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='director',
            name='ext_birth_place',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='director',
            name='ext_death_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='director',
            name='ext_imdb_id',
            field=models.CharField(blank=True, max_length=110),
        ),
        migrations.AddField(
            model_name='director',
            name='ext_name',
            field=models.CharField(blank=True, max_length=110),
        ),
        migrations.AddField(
            model_name='director',
            name='ext_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director',
            name='ext_picture_uri',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='director',
            name='ext_tmdb_id',
            field=models.CharField(blank=True, max_length=110),
        ),
        migrations.AddField(
            model_name='movie',
            name='ext_genres',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='movie',
            name='ext_imdb_id',
            field=models.CharField(blank=True, max_length=110),
        ),
        migrations.AddField(
            model_name='movie',
            name='ext_is_orig_title_diff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='ext_orig_lang',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='ext_orig_title',
            field=models.CharField(blank=True, max_length=110),
        ),
        migrations.AddField(
            model_name='movie',
            name='ext_overview',
            field=models.CharField(blank=True, max_length=8000),
        ),
        migrations.AddField(
            model_name='movie',
            name='ext_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='ext_picture_uri',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='movie',
            name='ext_release_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='ext_runtime',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='movie',
            name='ext_title',
            field=models.CharField(blank=True, max_length=110),
        ),
        migrations.AddField(
            model_name='movie',
            name='ext_tmdb_id',
            field=models.CharField(blank=True, max_length=110),
        ),
    ]
