# Generated by Django 6.1.1 on 2026-10-02 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_actor_ext_biography_actor_ext_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='auto_fetch_ext_resources_limit',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='settings',
            name='auto_fetch_ext_resources_sleep',
            field=models.IntegerField(default=9, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
